### PR TITLE
Platformio

### PR DESCRIPTION
**Pull request by playground**
Add PlatformIO support to develop/build firmware.

### CODE REVIEW

**Comment by illperipherals** [comment]
image

**Comment by illperipherals** [comment]
Flashes alright on the esp32-cams we picked up.

**Comment by illperipherals** [comment]
And BLE looks good. Nicely done, Jeff!
image
image

**Comment by illperipherals** [comment]
telegram-cloud-photo-size-1-5147667718034533155-y
LFG!

**Review by Gaurav-Ramakrishna — APPROVED** [review]

**Pull request merged**
